package rules

// ChinaRules returns the list of Chinese cloud provider detection rules.
// These cover major Chinese cloud service providers and platforms.
func ChinaRules() []Rule {
	return []Rule{
		{
			ID:          "CN-001",
			Name:        "Alibaba Cloud AccessKey ID",
			Description: "Detected Alibaba Cloud (Aliyun) AccessKey ID (starts with LTAI)",
			Severity:    SeverityHigh,
			Category:    CategoryChina,
			Keywords:    []string{"LTAI"},
			Pattern:     `LTAI[A-Za-z0-9]{12,}`,
			ChineseName: "阿里云 AccessKey ID",
		},
		{
			ID:          "CN-002",
			Name:        "Alibaba Cloud AccessKey Secret",
			Description: "Detected Alibaba Cloud (Aliyun) AccessKey Secret",
			Severity:    SeverityCritical,
			Category:    CategoryChina,
			Keywords:    []string{"access_key_secret", "AccessKeySecret", "AccessKeyId"},
			Pattern:     `(?:access_key_secret|AccessKeySecret|AccessKeySecret)\s*[=:]\s*["']?[A-Za-z0-9]{30}["']?`,
			ChineseName: "阿里云 AccessKey Secret",
		},
		{
			ID:          "CN-003",
			Name:        "Tencent Cloud SecretId",
			Description: "Detected Tencent Cloud SecretId (starts with AKID)",
			Severity:    SeverityHigh,
			Category:    CategoryChina,
			Keywords:    []string{"AKID"},
			Pattern:     `AKID[A-Za-z0-9]{12,}`,
			ChineseName: "腾讯云 SecretId",
		},
		{
			ID:          "CN-004",
			Name:        "Tencent Cloud SecretKey",
			Description: "Detected Tencent Cloud SecretKey",
			Severity:    SeverityCritical,
			Category:    CategoryChina,
			Keywords:    []string{"SecretKey", "secret_key", "TENCENT_SECRET_KEY"},
			Pattern:     `(?:SecretKey|secret_key|TENCENT_SECRET_KEY)\s*[=:]\s*["']?[A-Za-z0-9]{30,}["']?`,
			ChineseName: "腾讯云 SecretKey",
		},
		{
			ID:          "CN-005",
			Name:        "Huawei Cloud Access Key ID",
			Description: "Detected Huawei Cloud Access Key ID (starts with AKIA or similar Huawei pattern)",
			Severity:    SeverityHigh,
			Category:    CategoryChina,
			Keywords:    []string{"HWIA", "UDSIAM"},
			Pattern:     `(?:HWIA|UDSIAM)[A-Za-z0-9]{12,}`,
			ChineseName: "华为云 Access Key ID",
		},
		{
			ID:          "CN-006",
			Name:        "Huawei Cloud Secret Access Key",
			Description: "Detected Huawei Cloud Secret Access Key",
			Severity:    SeverityCritical,
			Category:    CategoryChina,
			Keywords:    []string{"HW_SECRET", "huawei_secret", "HWSecretAccessKey"},
			Pattern:     `(?:HW_SECRET|huawei_secret|HWSecretAccessKey)\s*[=:]\s*["']?[A-Za-z0-9]{30,}["']?`,
			ChineseName: "华为云 Secret Access Key",
		},
		{
			ID:          "CN-007",
			Name:        "Baidu Cloud API Key",
			Description: "Detected Baidu Cloud (BCE) API Key",
			Severity:    SeverityHigh,
			Category:    CategoryChina,
			Keywords:    []string{"bce-api-key", "baidu_api_key", "bce-v3"},
			Pattern:     `(?:bce-api-key|baidu_api_key|bce-v3/)[A-Za-z0-9\-]{32,}`,
			ChineseName: "百度云 API Key",
		},
		{
			ID:          "CN-008",
			Name:        "Baidu Cloud Secret Key",
			Description: "Detected Baidu Cloud (BCE) Secret Key",
			Severity:    SeverityCritical,
			Category:    CategoryChina,
			Keywords:    []string{"bce-secret-key", "baidu_secret_key"},
			Pattern:     `(?:bce-secret-key|baidu_secret_key)\s*[=:]\s*["']?[A-Za-z0-9]{32,}["']?`,
			ChineseName: "百度云 Secret Key",
		},
		{
			ID:          "CN-009",
			Name:        "UpYun Operator",
			Description: "Detected UpYun (Youpaiyun) Operator name",
			Severity:    SeverityMedium,
			Category:    CategoryChina,
			Keywords:    []string{"upyun", "UPYUN"},
			Pattern:     `(?:upyun|UPYUN)[-_]?operator\s*[=:]\s*["']?[A-Za-z0-9]+["']?`,
			ChineseName: "又拍云 Operator",
		},
		{
			ID:          "CN-010",
			Name:        "UpYun Password",
			Description: "Detected UpYun (Youpaiyun) Password",
			Severity:    SeverityHigh,
			Category:    CategoryChina,
			Keywords:    []string{"upyun", "UPYUN"},
			Pattern:     `(?:upyun|UPYUN)[-_]?password\s*[=:]\s*["']?[A-Za-z0-9+/=]{20,}["']?`,
			ChineseName: "又拍云 Password",
		},
		{
			ID:          "CN-011",
			Name:        "Qiniu AccessKey",
			Description: "Detected Qiniu Cloud (Qiniu) AccessKey",
			Severity:    SeverityHigh,
			Category:    CategoryChina,
			Keywords:    []string{"qiniu", "QINIU", "QiniuAccessKey"},
			Pattern:     `(?:qiniu|QINIU|QiniuAccessKey|access_key)\s*[=:]\s*["']?[A-Za-z0-9\-_]{20,}["']?`,
			ChineseName: "七牛云 AccessKey",
		},
		{
			ID:          "CN-012",
			Name:        "Qiniu SecretKey",
			Description: "Detected Qiniu Cloud (Qiniu) SecretKey",
			Severity:    SeverityCritical,
			Category:    CategoryChina,
			Keywords:    []string{"qiniu", "QINIU", "QiniuSecretKey", "secret_key"},
			Pattern:     `(?:QiniuSecretKey|qiniu_secret_key|SecretKey)\s*[=:]\s*["']?[A-Za-z0-9\-_]{28,}["']?`,
			ChineseName: "七牛云 SecretKey",
		},
		{
			ID:          "CN-013",
			Name:        "Sina Cloud Access Key",
			Description: "Detected Sina Cloud (SAE) Access Key",
			Severity:    SeverityMedium,
			Category:    CategoryChina,
			Keywords:    []string{"sina", "SINA", "sae_access_key"},
			Pattern:     `(?:sae_access_key|SINA_ACCESS_KEY|sinaaccesskey)\s*[=:]\s*["']?[A-Za-z0-9]{16,}["']?`,
			ChineseName: "新浪云 Access Key",
		},
		{
			ID:          "CN-014",
			Name:        "JD Cloud Access Key",
			Description: "Detected JD Cloud Access Key (starts with JDCLOUD)",
			Severity:    SeverityHigh,
			Category:    CategoryChina,
			Keywords:    []string{"JDCLOUD"},
			Pattern:     `JDCLOUD[A-Za-z0-9]{12,}`,
			ChineseName: "京东云 Access Key",
		},
		{
			ID:          "CN-015",
			Name:        "JD Cloud Secret Key",
			Description: "Detected JD Cloud Secret Key",
			Severity:    SeverityCritical,
			Category:    CategoryChina,
			Keywords:    []string{"JD_SECRET", "jdcloud_secret", "JDSecretKey"},
			Pattern:     `(?:JD_SECRET|jdcloud_secret|JDSecretKey)\s*[=:]\s*["']?[A-Za-z0-9]{28,}["']?`,
			ChineseName: "京东云 Secret Key",
		},
		{
			ID:          "CN-016",
			Name:        "Kingsoft Cloud AK",
			Description: "Detected Kingsoft Cloud (KS3) Access Key",
			Severity:    SeverityHigh,
			Category:    CategoryChina,
			Keywords:    []string{"ks3", "KS3", "kingsoft", "KSC"},
			Pattern:     `(?:ks3|KS3|kingsoft|KSC)[-_]?access[_-]?key\s*[=:]\s*["']?[A-Za-z0-9]{16,}["']?`,
			ChineseName: "金山云 AK",
		},
		{
			ID:          "CN-017",
			Name:        "Kingsoft Cloud SK",
			Description: "Detected Kingsoft Cloud (KS3) Secret Key",
			Severity:    SeverityCritical,
			Category:    CategoryChina,
			Keywords:    []string{"ks3", "KS3", "kingsoft", "KSC"},
			Pattern:     `(?:ks3|KS3|kingsoft|KSC)[-_]?secret[_-]?key\s*[=:]\s*["']?[A-Za-z0-9]{28,}["']?`,
			ChineseName: "金山云 SK",
		},
		{
			ID:          "CN-018",
			Name:        "MiniMax API Key",
			Description: "Detected MiniMax API Key",
			Severity:    SeverityHigh,
			Category:    CategoryChina,
			Keywords:    []string{"minimax", "MINIMAX", "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9"},
			Pattern:     `(?:minimax|MINIMAX)[-_]?api[_-]?key\s*[=:]\s*["']?[A-Za-z0-9\-_]{32,}["']?`,
			ChineseName: "MiniMax API Key",
		},
	}
}
