package rules

// GenericRules returns the list of generic/international detection rules.
// These cover common cloud providers, payment processors, and service credentials.
func GenericRules() []Rule {
	return []Rule{
		{
			ID:          "GEN-001",
			Name:        "AWS Access Key ID",
			Description: "Detected AWS Access Key ID (starts with AKIA)",
			Severity:    SeverityHigh,
			Category:    CategoryGeneric,
			Keywords:    []string{"AKIA"},
			Pattern:     `AKIA[0-9A-Z]{16}`,
			ChineseName: "AWS Access Key ID",
		},
		{
			ID:          "GEN-002",
			Name:        "AWS Secret Access Key",
			Description: "Detected AWS Secret Access Key (40-character base64 string near AWS key identifier)",
			Severity:    SeverityCritical,
			Category:    CategoryGeneric,
			Keywords:    []string{"aws_secret_access_key", "AWS_SECRET_ACCESS_KEY", "AwsSecretAccessKey", "secret_access_key"},
			Pattern:     `(?:aws_secret_access_key|AWS_SECRET_ACCESS_KEY|AwsSecretAccessKey|secret_access_key)\s*[=:]\s*["']?[A-Za-z0-9/+=]{40}["']?`,
			ChineseName: "AWS Secret Access Key",
		},
		{
			ID:          "GEN-003",
			Name:        "Google API Key",
			Description: "Detected Google API Key (starts with AIza)",
			Severity:    SeverityHigh,
			Category:    CategoryGeneric,
			Keywords:    []string{"AIza"},
			Pattern:     `AIza[0-9A-Za-z\-_]{35}`,
			ChineseName: "Google API Key",
		},
		{
			ID:          "GEN-004",
			Name:        "Google OAuth Token",
			Description: "Detected Google OAuth Access Token",
			Severity:    SeverityHigh,
			Category:    CategoryGeneric,
			Keywords:    []string{"ya29."},
			Pattern:     `ya29\.[0-9A-Za-z\-_]+`,
			ChineseName: "Google OAuth Token",
		},
		{
			ID:          "GEN-005",
			Name:        "Azure Client Secret",
			Description: "Detected Azure Client Secret",
			Severity:    SeverityHigh,
			Category:    CategoryGeneric,
			Keywords:    []string{"azure", "AZURE", "client_secret", "CLIENT_SECRET"},
			Pattern:     `(?:client_secret|CLIENT_SECRET|ClientSecret)\s*[=:]\s*["']?[A-Za-z0-9\-_~.]{36,}["']?`,
			ChineseName: "Azure Client Secret",
		},
		{
			ID:          "GEN-006",
			Name:        "Azure Connection String",
			Description: "Detected Azure Storage/Database Connection String",
			Severity:    SeverityHigh,
			Category:    CategoryGeneric,
			Keywords:    []string{"DefaultEndpointsProtocol", "AccountKey"},
			Pattern:     `DefaultEndpointsProtocol=https?;AccountName=[a-zA-Z0-9]+;AccountKey=[A-Za-z0-9+/=]+`,
			ChineseName: "Azure 连接字符串",
		},
		{
			ID:          "GEN-007",
			Name:        "Stripe API Key",
			Description: "Detected Stripe Secret API Key (starts with sk_live_)",
			Severity:    SeverityCritical,
			Category:    CategoryGeneric,
			Keywords:    []string{"sk_live_"},
			Pattern:     `sk_live_[0-9a-zA-Z]{24,}`,
			ChineseName: "Stripe API Key",
		},
		{
			ID:          "GEN-008",
			Name:        "Stripe Publishable Key",
			Description: "Detected Stripe Publishable Key (starts with pk_live_)",
			Severity:    SeverityMedium,
			Category:    CategoryGeneric,
			Keywords:    []string{"pk_live_"},
			Pattern:     `pk_live_[0-9a-zA-Z]{24,}`,
			ChineseName: "Stripe Publishable Key",
		},
		{
			ID:          "GEN-009",
			Name:        "GitHub Token",
			Description: "Detected GitHub Personal Access Token or OAuth Token",
			Severity:    SeverityCritical,
			Category:    CategoryGeneric,
			Keywords:    []string{"ghp_", "gho_", "ghu_", "ghs_", "ghr_"},
			Pattern:     `gh[psour]_[A-Za-z0-9_]{36,}`,
			ChineseName: "GitHub Token",
		},
		{
			ID:          "GEN-010",
			Name:        "GitLab Token",
			Description: "Detected GitLab Personal Access Token or OAuth Token",
			Severity:    SeverityCritical,
			Category:    CategoryGeneric,
			Keywords:    []string{"glpat-", "glptt-"},
			Pattern:     `glp[aot][\-_][A-Za-z0-9\-_]{20,}`,
			ChineseName: "GitLab Token",
		},
		{
			ID:          "GEN-011",
			Name:        "Slack Token",
			Description: "Detected Slack Bot Token or User Token",
			Severity:    SeverityHigh,
			Category:    CategoryGeneric,
			Keywords:    []string{"xoxb-", "xoxp-", "xoxa-", "xoxr-"},
			Pattern:     `xox[bpar]-[0-9a-zA-Z\-]{10,}`,
			ChineseName: "Slack Token",
		},
		{
			ID:          "GEN-012",
			Name:        "Slack Webhook",
			Description: "Detected Slack Webhook URL",
			Severity:    SeverityMedium,
			Category:    CategoryGeneric,
			Keywords:    []string{"hooks.slack.com"},
			Pattern:     `https://hooks\.slack\.com/services/T[A-Z0-9]+/B[A-Z0-9]+/[A-Za-z0-9]+`,
			ChineseName: "Slack Webhook",
		},
		{
			ID:          "GEN-013",
			Name:        "Twilio API Key",
			Description: "Detected Twilio API Key (starts with SK)",
			Severity:    SeverityHigh,
			Category:    CategoryGeneric,
			Keywords:    []string{"SK", "twilio"},
			Pattern:     `SK[0-9a-fA-F]{32}`,
			ChineseName: "Twilio API Key",
		},
		{
			ID:          "GEN-014",
			Name:        "SendGrid API Key",
			Description: "Detected SendGrid API Key",
			Severity:    SeverityHigh,
			Category:    CategoryGeneric,
			Keywords:    []string{"SG.", "sendgrid"},
			Pattern:     `SG\.[A-Za-z0-9\-_]{22}\.[A-Za-z0-9\-_]{43}`,
			ChineseName: "SendGrid API Key",
		},
		{
			ID:          "GEN-015",
			Name:        "Mailgun API Key",
			Description: "Detected Mailgun API Key (starts with key-)",
			Severity:    SeverityHigh,
			Category:    CategoryGeneric,
			Keywords:    []string{"key-", "mailgun"},
			Pattern:     `key-[0-9a-zA-Z]{32}`,
			ChineseName: "Mailgun API Key",
		},
		{
			ID:          "GEN-016",
			Name:        "PostgreSQL Connection String",
			Description: "Detected PostgreSQL connection string with embedded credentials",
			Severity:    SeverityHigh,
			Category:    CategoryGeneric,
			Keywords:    []string{"postgresql://", "postgres://"},
			Pattern:     `(?:postgresql|postgres)://[^\s"']+:[^\s"']+@[^\s"']+`,
			ChineseName: "PostgreSQL 连接字符串",
		},
		{
			ID:          "GEN-017",
			Name:        "MongoDB Connection URI",
			Description: "Detected MongoDB connection URI with embedded credentials",
			Severity:    SeverityHigh,
			Category:    CategoryGeneric,
			Keywords:    []string{"mongodb://", "mongodb+srv://"},
			Pattern:     `mongodb(?:\+srv)?://[^\s"']+:[^\s"']+@[^\s"']+`,
			ChineseName: "MongoDB 连接URI",
		},
		{
			ID:          "GEN-018",
			Name:        "Redis URL with Password",
			Description: "Detected Redis URL with embedded password",
			Severity:    SeverityHigh,
			Category:    CategoryGeneric,
			Keywords:    []string{"redis://"},
			Pattern:     `redis://[^\s"']+:[^\s"']+@[^\s"']+`,
			ChineseName: "Redis URL（含密码）",
		},
		{
			ID:          "GEN-019",
			Name:        "Private SSH Key (RSA)",
			Description: "Detected RSA private SSH key",
			Severity:    SeverityCritical,
			Category:    CategoryGeneric,
			Keywords:    []string{"BEGIN RSA PRIVATE KEY"},
			Pattern:     `-----BEGIN RSA PRIVATE KEY-----`,
			ChineseName: "RSA 私钥",
		},
		{
			ID:          "GEN-020",
			Name:        "Private SSH Key (EC)",
			Description: "Detected EC private SSH key",
			Severity:    SeverityCritical,
			Category:    CategoryGeneric,
			Keywords:    []string{"BEGIN EC PRIVATE KEY"},
			Pattern:     `-----BEGIN EC PRIVATE KEY-----`,
			ChineseName: "EC 私钥",
		},
		{
			ID:          "GEN-021",
			Name:        "Private SSH Key (Ed25519/OpenSSH)",
			Description: "Detected OpenSSH private key",
			Severity:    SeverityCritical,
			Category:    CategoryGeneric,
			Keywords:    []string{"BEGIN OPENSSH PRIVATE KEY"},
			Pattern:     `-----BEGIN OPENSSH PRIVATE KEY-----`,
			ChineseName: "OpenSSH 私钥",
		},
		{
			ID:          "GEN-022",
			Name:        "Private SSH Key (DSA)",
			Description: "Detected DSA private SSH key",
			Severity:    SeverityCritical,
			Category:    CategoryGeneric,
			Keywords:    []string{"BEGIN DSA PRIVATE KEY"},
			Pattern:     `-----BEGIN DSA PRIVATE KEY-----`,
			ChineseName: "DSA 私钥",
		},
		{
			ID:          "GEN-023",
			Name:        "Private SSH Key (PKCS8)",
			Description: "Detected PKCS8 private key",
			Severity:    SeverityCritical,
			Category:    CategoryGeneric,
			Keywords:    []string{"BEGIN PRIVATE KEY"},
			Pattern:     `-----BEGIN PRIVATE KEY-----`,
			ChineseName: "PKCS8 私钥",
		},
		{
			ID:          "GEN-024",
			Name:        "JWT Token",
			Description: "Detected JSON Web Token (JWT)",
			Severity:    SeverityMedium,
			Category:    CategoryGeneric,
			Keywords:    []string{"eyJ"},
			Pattern:     `eyJ[A-Za-z0-9\-_]+\.eyJ[A-Za-z0-9\-_]+\.[A-Za-z0-9\-_]+`,
			ChineseName: "JWT Token",
		},
	}
}
